### ISSUE TITLE
Express server does not work on MacOS

### ISSUE THREAD

**Issue by manhtien2607** [mintuz/BB8-Commander#16] opened 2016-03-08 20:42 UTC
Send sphero and custom command via json api does not work. Logs show actions name but does not send to BB8
Trying to debug on Eclipse to see which step causes this issue
Any suggestion is appreciated 
Thanks

**Comment by mintuz** [comment] 2016-03-08 20:45
Do any of the other commands work? could you delete ~/.bb8config and use the connect action again.

**Comment by manhtien2607** [comment] 2016-03-08 20:47
Direct command from terminal work perfectly ( eg: node index.js roll) 
Tried to send setup command via RestAPI in case Express server use different config. But it did not help

**Comment by mintuz** [comment] 2016-03-08 20:52
You might have already tried this but can you send this in the request body. And report back with the response and anything that is outputted to the console.

```
{"mode":"sphero", "action":"roll", "value": [10,180]}
```

Also

```
{
  "mode":"custom",
  "command":"disco"
}
```

**Comment by manhtien2607** [comment] 2016-03-08 20:55
With sphero command it returns
 {
  "error": {}
}

For custom command it returns
Command Executed - disco

Setup command via RestAPI standing at "beginning setup" ; does it is required to setup environment variable again in Express server?

**Comment by mintuz** [comment] 2016-03-08 21:00
The setup command should only be run via the terminal and not the express server. With the disco command, does your BB8 start flashing different colours?
1. delete ~/.bb8config
2. `setup command`
3. Make sure your BB8 Config is setup correctly.
4. Run express server action
5. Retry sending a command.

**Comment by manhtien2607** [comment] 2016-03-08 21:17
I do it all over again. When start express server, BB8 lightup, but i does not receive any other commands via Rest API

**Comment by manhtien2607** [comment] 2016-03-08 21:18
Is there anyway to debug Express server in Eclipse, where does npm install put dependency library, so i can add it onto Eclipse project?

**Comment by mintuz** [comment] 2016-03-08 21:20
So I'm not sure about Eclipse (I use a mixture of Atom and Sublime) but you can debug it with Chrome by following these steps.
1. `npm install -g node-inspector`
2. `node-debug index.js express`

This will open up chrome pointing to your code, at this point you can now just add breakpoints as you would normally in Chrome.

Also can you give me the output of 
1. `npm -v`
2. `node -v`

**Comment by manhtien2607** [comment] 2016-03-08 21:22
that is great, i will start with that, thanks for your super quick and detail response. Hope i can close this issue today

**Comment by manhtien2607** [comment] 2016-03-09 00:25
in express script, i found that every request is checked with requestBody.command ; but we haven't include this onto request body. 
requestBody.command && requestBody.mode === 'sphero' 
So it always ignore this

**Comment by manhtien2607** [comment] 2016-03-09 00:53
i test again, send Rest API request for 

{
  "mode":"custom",
  "command":"roll"
}

Debug goes to bb8.roll(150, direction); which should control bb8 the same like using node index.js roll from terminal. 
Really stuck at this

**Comment by mintuz** [comment] 2016-03-09 07:08
I will take a look tonight for you. See if it's reproduceable, however if it getting to the bb8.roll command I imagine it's either your BB8 not connecting properly or a bug with Sphero SDK (BB8 Support is still experimental)

**Comment by mintuz** [comment] 2016-03-15 16:57
@manhtien2607 I've looked into this and can't reproduce it on my machine. The fact the debug goes to the line where we call `bb8.roll(150, direction)` suggests your BB8 is not connecting properly to your machine or you're pulling down a different version of the Sphero SDK.

**Comment by Sud-Puth** [comment] 2016-03-16 01:23
@manhtien2607 I checked too, and it works good. Are you connecting to the BB8 on your phone and also trying to issue the commands from your machine ?

**Comment by mintuz** [comment] 2016-08-27 08:03
Closing issue since this no longer seems to be an issue.

**Closed as completed by mintuz** 2016-08-27 08:03 UTC
